# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DBMS_Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DBMS_Project
	pod 'SnapKit'
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'Alamofire'
	pod 'SVProgressHUD'
	pod 'DLRadioButton', '~> 1.4'
end
